Update decoder.rs
I had following error when compiling on x86

error[E0063]: missing field safe in initializer of Config
   --> /home/volumio/.cargo/registry/src/index.crates.io-6f17d22bba15001f/bliss-audio-0.8.0/src/song/decoder.rs:458:39
    |
458 |                 context.set_threading(Config {
    |                                       ^^^^^^ missing safe